<?php

namespace EavBundle\Entity;

/**
 * EavEntityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EavEntityRepository extends \Doctrine\ORM\EntityRepository
{
}
