<?php

namespace ServicebookBundle\Entity;

/**
 * BrandVinRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BrandVinRepository extends \Doctrine\ORM\EntityRepository
{
}
