<?php

namespace ServicebookBundle\Entity;

/**
 * BrandServiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BrandServiceRepository extends \Doctrine\ORM\EntityRepository
{
}
