<?php

namespace ServicebookBundle\Entity;
use AppBundle\Entity\Repository;
/**
 * BrandServiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BrandServiceRepository extends Repository {
    
}
