<?php

namespace ServicebookBundle\Entity;

use AppBundle\Entity\Repository;

/**
 * BrandServiceActionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BrandServiceActionRepository extends Repository {
    
}
