<?php

namespace ServicebookBundle\Entity;

/**
 * RegionCityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RegionCityRepository extends \Doctrine\ORM\EntityRepository
{
}
