<?php

namespace ServicebookBundle\Entity;

/**
 * WorkshopServicePartRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WorkshopServicePartRepository extends \Doctrine\ORM\EntityRepository
{
}
