<?php

namespace ServicebookBundle\Entity;

use AppBundle\Entity\Repository;

/**
 * WorkshopRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WorkshopRepository extends Repository {
    
}
