<?php

namespace ServicebookBundle\Entity;

use AppBundle\Entity\Repository;
/**
 * WorkshopServiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WorkshopServiceRepository extends Repository
{
}
