<?php

namespace ServicebookBundle\Entity;

/**
 * WorkshopServiceActionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WorkshopServiceActionRepository extends \Doctrine\ORM\EntityRepository
{
}
