<?php

namespace ServicebookBundle\Entity;

/**
 * WorkshopServiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WorkshopServiceRepository extends \Doctrine\ORM\EntityRepository
{
}
