<?php

namespace ServicebookBundle\Entity;

use AppBundle\Entity\Repository;

/**
 * WorkshopPartRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WorkshopPartRepository extends Repository {
    
}
