<?php

namespace AppBundle\Entity;

use AppBundle\Entity\Repository;
/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends Repository {
    
}
