servivebook:
    resource: "@ServicebookBundle/Controller/"
    type:     annotation
    prefix:   /
    
admin:
    resource: "@AdminBundle/Controller/"
    type:     annotation
    prefix:   /

access:
    resource: "@AccessBundle/Resources/config/routing.yml"
    prefix:   /



app:
    resource: "@AppBundle/Controller/"
    type:     annotation
