<?php

namespace AppBundle\Entity;

/**
 * OrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Repository extends \Doctrine\ORM\EntityRepository {

    
    public function recordsTotal() {
        $result = $this->getEntityManager()
                ->createQuery('SELECT count(p) as cnt FROM '.$this->_entityName.' p')
                ->getResult();
        return $result[0]["cnt"];
    }

    public function recordsFiltered($where) {
        $result = $this->getEntityManager()
                ->createQuery('SELECT count(p) as cnt FROM '.$this->_entityName.' p ' . $where)
                ->getResult();
        return $result[0]["cnt"];
    }

}
