<?php

namespace AppBundle\Entity;

use AppBundle\Entity\Repository;
/**
 * SettingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SettingRepository extends Repository {
    
}
